import './cluster/KMeans.test'
import './compose/ColumnTransformer.test'
import './datasets/makeRegression.test'
import './dummy/DummyClassifier.test'
import './dummy/DummyRegressor.test'
import './ensemble/VotingClassifier.test'
import './ensemble/VotingRegressor.test'
import './impute/SimpleImputer.test'
import './linear_model/LinearRegression.test'
import './linear_model/LogisticRegression.test'
import './metrics/metrics.test'
// import './model_selection/KFold.test'
import './model_selection/trainTestSplit.test'
import './naive_bayes/GaussianNB.test'
/* When we figure out how to do expect.extend in karma */
// import './neighbors/bruteNeighborhood.test'
// import './neighbors/cappedMaxHeap.test'
// import './neighbors/kdTree.test'
// import './neighbors/kNeighborsClassifier.test'
// import './neighbors/kNeighborsRegressor.test'
// import './neighbors/metrics.test'
import './pipeline/Pipeline.test'
import './preprocessing/LabelEncoder.test'
import './preprocessing/MaxAbsScaler.test'
import './preprocessing/MinMaxScaler.test'
import './preprocessing/Normalizer.test'
import './preprocessing/OneHotEncoder.test'
import './preprocessing/OrdinalEncoder.test'
import './preprocessing/RobustScaler.test'
import './preprocessing/StandardScaler.test'
import './svm/LinearSVC.test'
import './svm/LinearSVR.test'
/* When we put back in the SVM code */
// import './svm/SVC.test'
// import './svm/SVR.test'
import './tree/Criterion.test'
// import './tree/DecisionTree.test'
import './tree/Splitter.test'
/* When we use the expect.extend stuff */
// import './jestTensorMatchers.test'
