import './cluster/kmeans.test'
import './compose/columnTransformer.test'
import './datasets/makeRegression.test'
import './dummy/dummyClassifier.test'
import './dummy/dummyRegressor.test'
import './ensemble/votingClassifier.test'
import './ensemble/votingRegressor.test'
import './impute/simpleImputer.test'
import './linear_model/linearRegression.test'
/* When we figure out why we can't save / load logistic regressions */
// import './linear_model/logisticRegression.test'
import './metrics/metrics.test'
// import './model_selection/kFold.test'
import './model_selection/trainTestSplit.test'
import './naive_bayes/gaussianNaiveBayes.test'
/* When we figure out how to do expect.extend in karma */
// import './neighbors/bruteNeighborhood.test'
// import './neighbors/cappedMaxHeap.test'
// import './neighbors/kdTree.test'
// import './neighbors/kNeighborsClassifier.test'
// import './neighbors/kNeighborsRegressor.test'
// import './neighbors/metrics.test'
import './pipeline/pipeline.test'
import './preprocessing/labelEncoder.test'
import './preprocessing/maxAbsScaler.test'
import './preprocessing/minMaxScaler.test'
import './preprocessing/normalizer.test'
import './preprocessing/oneHotEncoder.test'
import './preprocessing/ordinalEncoder.test'
import './preprocessing/robustScaler.test'
import './preprocessing/standardScaler.test'
import './svm/linearSVC.test'
import './svm/linearSVR.test'
/* When we put back in the SVM code */
// import './svm/SVC.test'
// import './svm/SVR.test'
import './tree/criterion.test'
// import './tree/decisiontree.test'
import './tree/splitter.test'
/* When we use the expect.extend stuff */
// import './jestTensorMatchers.test'
